// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SenseedDataCenter.Models;

namespace SenseedDataCenter.Migrations
{
    [DbContext(typeof(SenseedDataCenterContext))]
    [Migration("20181119060058_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SenseedDataCenter.Models.AnemometerRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Direction");

                    b.Property<float>("E2W");

                    b.Property<float>("N2S");

                    b.Property<DateTime>("RecordDate")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<float>("SoundVelocity");

                    b.Property<float>("Velocity");

                    b.HasKey("Id");

                    b.ToTable("AnemometerRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
